batch_sizes:
  - 1

num_clients:
  - 1

max_output_tokens:
  - 200

lambdas:
        #  - 0.11
        #- 0.23
        #- 0.34
        #- 0.46
        #- 0.57
        #- 0.69
        #- 0.8
        #- 0.92
  - 1.03
  - 1.14
  - 1.26
    #- 1.37

deltas:
  - 2
